on:
  push:
    branches:
      - main
env:
  IMAGE_NAME: lambda-docker
  AWS_ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
jobs:
  docker:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker build
        run: docker build . -t $AWS_ECR_REGISTRY/$IMAGE_NAME:${{ github.sha }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/lambda-docker-github-actions-oidc
      - name: Login to ECR
        run: aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin $AWS_ECR_REGISTRY
      - name: Docker push
        run: docker push $AWS_ECR_REGISTRY/$IMAGE_NAME:${{ github.sha }}
  lambda:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    needs: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/lambda-docker-github-actions-oidc
      - name: Deploy Lambda
        run: |
          aws lambda update-function-code \
            --function-name lambda-docker \
            --image-uri $AWS_ECR_REGISTRY/$IMAGE_NAME:${{ github.sha }}
